export const REC_WEIGHTS = {
  HIGH_YIELD_BONUS: 20,
  PYQ_WEIGHT_MULTIPLIER: 5,
  WEAK_CONFIDENCE_BONUS: 45,
  PENDING_CONTENT_BONUS: 25,
  PENDING_QBANK_BONUS: 20,
  REVISION_DUE_BONUS: 40,
  MASTERED_PENALTY: -50,
  UNEXPLORED_TOPIC_BONUS: 15,
  INCOMPLETE_SYSTEM_BONUS: 25,
  DEFAULT_SUBJECT_WEIGHT: 65,
};

export const REC_MULTIPLIERS = {
  YEAR_ALIGN_EXACT_1ST_2ND: 2.5,
  YEAR_ALIGN_EXACT_3RD: 2.5,
  YEAR_ALIGN_EXACT_FINAL: 2.2,
  YEAR_ALIGN_GOOD: 1.5,
  YEAR_ALIGN_MODERATE: 1.2,
  YEAR_ALIGN_SLIGHT: 1.1,
  YEAR_ALIGN_NEUTRAL: 1.0,
  YEAR_ALIGN_LOW: 0.5,
  YEAR_ALIGN_VERY_LOW: 0.4,
  YEAR_ALIGN_MINIMAL: 0.3,
  YEAR_ALIGN_AVOID: 0.2,
};
